# Generated by Django 4.1.1 on 2022-09-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=8)),
                ('ConfirmPassword', models.CharField(max_length=8)),
                ('MobileNo', models.CharField(max_length=10)),
            ],
        ),
    ]
