# Generated by Django 4.1.1 on 2022-09-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_article_delete_createaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.TextField(max_length=150)),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
