# Generated by Django 4.1.1 on 2022-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='MobileNo',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
