# Generated by Django 4.1.1 on 2022-09-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_add_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createaccount',
            name='MobileNo',
            field=models.PositiveIntegerField(),
        ),
    ]
