# Generated by Django 4.1.1 on 2022-09-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_alter_createaccount_mobileno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_To_Cart',
        ),
    ]
