# Generated by Django 4.1.1 on 2022-09-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_add_to_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_to_cart',
            name='Price',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='add_to_cart',
            name='Quantity',
            field=models.CharField(max_length=10),
        ),
    ]
