# Generated by Django 4.1.1 on 2022-09-20 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0011_alter_add_to_cart_price_alter_add_to_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateAccount',
        ),
    ]
