# Generated by Django 4.1.1 on 2022-09-21 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
